### ISSUE TITLE
create Books page

### ISSUE THREAD

**Issue by rkuhn** [akka/akka.github.com#120]
On Akka:
- Akka Concurrency (Derek Wyatt)
- Effective Akka (Jamie Allen)
- Akka in Action (Raymond Roestenburg)
- Akka Essentials (Kumar Gupta Munish)
- Developing an Akka Edge (Thomas Lockney & Raymond Tay)

On Reactive Applications:
- Reactive Design Patterns (Roland Kuhn & Jamie Allen)
- Reactive Enterprise with Actor Model: Application and Integration Patterns for Scala and Akka (Vaughn Vernon; this one is vaporware ATM)

possibly include some reading list on DDD, CQRS/ES, distributed systems

**Comment by johanandren** [comment]
Going through and closing tickets that are done away with new page.
