### ISSUE TITLE
Every documentation page shows "Loading" directly above the heading

### ISSUE THREAD

**Issue by jrudolph** [akka/akka.github.com#226]
![screenshot from 2015-07-15 15 00 15](https://cloud.githubusercontent.com/assets/9868/8698981/6e17cdac-2b02-11e5-85b5-3084bfb52f94.png)

**Comment by ktoso** [comment]
Works for me on chrome... Seems you're not getting the search bar?

![java_documentation_ _akka_documentation](https://cloud.githubusercontent.com/assets/120979/8699595/e47d6e76-2b06-11e5-9e97-24e9df35c8c4.png)

**Comment by jrudolph** [comment]
Ah, I'm blocking the search bar. Sorry for the noise.

**Comment by ktoso** [comment]
Ok, thanks! No problem, thanks for rising the issue, could have been something wrong on the page :)
