### ISSUE TITLE
Dependencies list

### ISSUE THREAD

**Issue by DGolubets** [akka/akka.github.com#300]
Hi guys.

Every now and then when I'm adding Akka to a new project I have a hard time looking for dependency names. I end up going to search.maven.org and search there. Though it feels wrong.

I understand  that Akka follows a pattern in naming their modules. But then one should figure the name of module, also remember the group name and etc.

I always appreciate when a developer of a library gives an SBT libraryDependencies code which can be just copy pasted. I think Akka should not be an exception.

As I see it, you can make a section in download, which will have this info for every module, or even better - a dynamic UI with checkboxes to generate libraryDependencies.

**Comment by ktoso** [comment]
Yes we want to add that.
The problem is either I hack on a feature for Akka, or I work on the website – you can guess what ends up winning most of the time.

Would you be able to help out on this one? 
A section with the artifact names nice on top of the site would be excellent.

**Comment by DGolubets** [comment]
Ok, I'll try to get my hands on it when I have time.

**Comment by ktoso** [comment]
Seems I was faster https://github.com/akka/akka.github.com/pull/304 :-)
However any help on making it look better and nicer to use would be much appreciated, thanks in advance!
