### ISSUE TITLE
Broken link in a tutorial in the docs

### ISSUE THREAD

**Issue by GMadorell** [akka/akka.github.com#335]
Hey!

I was just browsing a tutorial in the akka documentation (http://doc.akka.io/docs/akka/2.0/intro/getting-started-first-scala.html). 

The tutorial suggests to clone code from https://github.com/akka/akka/tree/master/akka-tutorials/akka-tutorial-first, which doesn't exist.

**Comment by patriknw** [comment]
Please use latest documentation, http://doc.akka.io/docs/akka/2.4/
