### ISSUE TITLE
Give some kind of feedback when trying to send a non-serializable object

### ISSUE THREAD

**Issue by Vocht** [akka/akka.github.com#337]
There is no point in sending an object which is not serializable. But you are able to do so anyway. When you do that, nothing happens. Some kind of feedback could be given to indicate to the user that they are not sending a serializible.

An exception could be thrown, or even a warning in the compiler.

**Comment by drewhk** [comment]
This is not the repo you want, this is hosting the website. See https://github.com/akka/akka/issues/

**Comment by drewhk** [comment]
There cannot be a warning from the compiler as the available serializers are only known at runtime. The remote subsystem does log when you try to send something not serializable. The method "!" never throws, it is its contract and by design and will never change.
