### ISSUE TITLE
Make front page first load experience nicer

### ISSUE THREAD

**Issue by richdougherty** [akka/akka.github.com#35]
The front page looks nice, but exhibits a few loading artifacts, especially with an empty browser cache.
1. Some of the images are missing width/height, so they have to be downloaded before they can be laid out. This means the page moves around a bit while it's loading.
2. The drop shadow effect on the text relies on a dark background, but the background image takes a while to load. This makes the text appear to 'flash' on the screen. Might want to specify a solid background color in the CSS so the text effects look good even while the image is loading.

**Comment by johanandren** [comment]
Going through and closing tickets that are done away with new page.
