### ISSUE TITLE
Add "wget" tab instead of "link" tab on download page

### ISSUE THREAD

**Issue by jrudolph** [akka/akka.github.com#387]
![screenshot from 2017-05-09 18 13 52](https://cloud.githubusercontent.com/assets/9868/25860910/487942c8-34e3-11e7-803f-8602799f6e95.png)

The "link" tab isn't super useful and should probably replaced by the "wget" tab we have right now. Question is how to maintain the set of jars to put in there.

**Comment by ktoso** [comment]
> The "link" tab isn't super useful and should probably replaced by the "wget" tab we have right now.

Yes 👍 

>  Question is how to maintain the set of jars to put in there.

Not sure what you mean? The links are synthesised from the artifact names, which are defined in json, same as the artifacts for sbt/gradle/maven

**Comment by jrudolph** [comment]
> Not sure what you mean? The links are synthesised from the artifact names, which are defined in json, same as the artifacts for sbt/gradle/maven. It's not super precise - I mean, won't include their dependencies - I guess that's what you mean? I say we punt on that issue, if someone wants our jars, there they are.

The current page shows a line for every module in the project. Just recently people were missing the akka-parsing module from the akka-http list. But then, we don't want to distribute or show transitive dependencies so it's hard to say what the use of this tab is in the first place.

**Comment by johanandren** [comment]
Heh, I explicitly made it link instead of wget because I thought wget isn't very useful but people want the url to download with whatever they want. If people knows how to use wget they will know how to run it with an url, no?

**Comment by ktoso** [comment]
I don't have a strong enough opinion about that use case, whichever you both can agree on works IMO ;)

**Comment by johanandren** [comment]
For me it felt like this: "build tool", "build tool", "build tool", "how you can download with ms IE explorer"

**Comment by patriknw** [comment]
It's also a question of how useful those `wget` links actually are, you would also need all transitive dependencies to be able to do anything useful with the jars. The original request was when we removed the distribution zip for 2.5 and someone asked for downloads of all the jars (e.g. setting up a IDE project without a build).

**Comment by jrudolph** [comment]
Personally, I also don't care about these at all. However, we added the "wget" tab just recently because there seemed to be demand for a full-contained download link.

In the best case, we would either not offer this solution at all or really provide a full-blown distribution archive that also contains transitive third-party dependencies (but then we need to make sure to fulfill the license requirements for distribution).

**Comment by johanandren** [comment]
The full-blown distribution zip we moved away from since we couldn't really think of a use case common enough that it makes sense to have such a heavy build step when releasing. So maybe just remove these again then? I'm leaning towards if you need that, then you will have to figure out how to fetch all deps and transitive deps yourself.

**Comment by ktoso** [comment]
I would not mind removing again... It's such a mess if people actually do manage this manually..
We only added it back to calm down someone who was using it like that AFAIR

**Comment by ktoso** [comment]
Related:

Though for `dash` the author did request we provide the docs in a downloadable format:
https://github.com/akka/akka/issues/22728

**Comment by patriknw** [comment]
Documentation zip makes sense.

We could put a complete maven pom.xml here, with instruction to use `mvn dependency:copy-dependencies`
http://maven.apache.org/plugins/maven-dependency-plugin/usage.html

**Comment by johanandren** [comment]
So... I'll remove the tab and open a docs-zip ticket in akka/akka?

**Comment by ktoso** [comment]
Yes sounds good.

**Comment by patriknw** [comment]
The docs-zip ticket is https://github.com/akka/akka/issues/22728
