### ISSUE TITLE
Consolidate blog / news pages

### ISSUE THREAD

**Issue by jrudolph** [akka/akka.github.com#398]
Subitem of #390.

Right now there are several URLs that seem to contain similar but not quite the same contents:

 * http://jrudolph.github.io/akka.github.com/blog/ -> shows latest entry of news or blog item and two lists at the right side with "Latest News" and "Latest Blog"
 * http://jrudolph.github.io/akka.github.com/blog/news-archive.html -> shows a list of all news or blog items and the same side bar
 * http://jrudolph.github.io/akka.github.com/blog/article-archive.html -> shows a list of only article items and the same side bar
 * http://jrudolph.github.io/akka.github.com/news -> redirects to http://jrudolph.github.io/akka.github.com/blog/ (but broken at least on my copy)
 * http://jrudolph.github.io/akka.github.com/news/ -> shows a list of items (news and blog?) and a single block of "Latest articles" on the right side-bar
 * http://jrudolph.github.io/akka.github.com/news/
 * http://jrudolph.github.io/akka.github.com/news/all-news.html -> redirects to  http://jrudolph.github.io/akka.github.com/blog/news-archive.html (but broken at least on my copy)

**Comment by johanandren** [comment]
The idea is that both news and articles go in the same set, but we still want to be able to look at just news or just blog entries, that's why there is the two lists in the right hand, and an "archive" for each of those. I didn't know the redirects were broken though. Sounds like those make sense if they would work, no?

**Comment by johanandren** [comment]
Ok, so the redirect plugin does in fact not work on GitHub pages, I had my suspicions. I added it in _config.yml under `gems:` but I guess the only plugins you can use are the ones that the GitHub-pages-gem that the gemfile pulls in.

**Comment by johanandren** [comment]
This page seems to indicate it should work though: https://help.github.com/articles/redirects-on-github-pages/

**Comment by jrudolph** [comment]
I think it's actually a bug in the usage. Locally I cannot even generate the pages because the redirection seems wrong. It seems to work when I add a trailing slash to the redirected page here: https://github.com/akka/akka.github.com/blame/wip-new-layout-2017/blog/index.md#L4

**Comment by jrudolph** [comment]
The solution is just to remove the `/news` folder and add redirections to preserve the old links.
