### ISSUE TITLE
Docs page

### ISSUE THREAD

**Issue by johanandren** [akka/akka.github.com#408]
- [x] Is the list of boxes the right ones?
- [x] Should we use _data for this one as well? - blocked by alpakka being different than the others, I think it would be too many if-else to cover that one to make it nice.
- [x] Is the list of dependencies right for each module, should we include test kit deps
- [x] Make the getting started section stand out more
- [x] I think gradle import is incorrect, fix

**Comment by patriknw** [comment]
It's right boxes. Testkits when appropriate, eg actor, stream
