### ISSUE TITLE
"Try Akka" top level navigation

### ISSUE THREAD

**Issue by johanandren** [akka/akka.github.com#411]
> Shall we add Try Akka at the top, linking directly to the Quickstart page of the docs, similar to https://www.lagomframework.com/

I think we should!

**Comment by patriknw** [comment]
I thought some more about this when writing the Quickstart in the documentation: https://github.com/akka/akka/pull/22924/files#r116210990

Let's add a *Try Akka* page at the website that we can use as the Quickstart landing page, and also include the choice Java / Scala. Similar to https://www.lagomframework.com/get-started.html

The contents of the page after selecting Java / Scala can be similar to https://github.com/akka/akka/pull/22924, i.e. just a set of instructions, and linking to the Quickstart guide.
