### ISSUE TITLE
launch issues

### ISSUE THREAD

**Issue by johanandren** [akka/akka.github.com#422]
- [x] news aggregation in landing page links wrong
- [x] blog link in header links wrong
- [x] release versions needs update in config.yaml
- [x] doc links use version rather than current

**Comment by drewhk** [comment]
Docs layout is also weird:

![image](https://cloud.githubusercontent.com/assets/932285/26400887/756abef0-4083-11e7-905d-9fc97fb98d17.png)

As you see for some reason there is a large empty blob on the left that crams everything together (unnecessarily). This same empty space remains in the actual doc pages as well. Also, the entires in the box does not stand out as elements of an enumeration but as an unstructured blob.

Otherwise, I like where this going!

**Comment by patriknw** [comment]
* [ ] snapshot links are wrong in /other-releases.html http://doc.akka.io/docs/akka/snapshot/java.html
* [ ] s/SBT/sbt/ in /try-akka (and all other places)
* [ ] The links in the Alpakka box are strangely placed in /docs Chrome Version 58.0.3029.110 OSX

![screen shot 2017-05-24 at 13 16 24](https://cloud.githubusercontent.com/assets/336161/26400960/d7d3819e-4083-11e7-9415-89f23dfc7338.png)

**Comment by johanandren** [comment]
#423

**Comment by patriknw** [comment]
switch to landscape screen, @drewhk ;-)

thanks for feedback, we'll look into that

**Comment by patriknw** [comment]
@drewhk I think the space to the right is reserved for the side notes, that we haven't started using yet. https://github.com/akka/akka/issues/22906
It should scale with browser width, though. Might need some  adjustments.

**Comment by jrudolph** [comment]
[ ] News items (in contrast to blog entries) are not shown with the right template, missing the sidebar and borders, etc.
![screenshot from 2017-05-24 13 37 59](https://cloud.githubusercontent.com/assets/9868/26401445/4b7337f0-4086-11e7-87fe-64cc270d6237.png)

**Comment by patriknw** [comment]
* [ ] in addition to the news vs blog, seems like some news are under /blog/news, http://akka.io/news/2017/05/02/akka-2.5.1-released.html vs 
http://akka.io/blog/news/2017/05/03/akka-http-10.0.6-released.html

**Comment by 2m** [comment]
There is a duplicate entry to 10.0.6 security release on the akka.io/blog page
![untitled](https://cloud.githubusercontent.com/assets/422086/26401861/7ba9a4c2-4090-11e7-9434-3c7368692907.png)

**Comment by johanandren** [comment]
The template for news makes the navigation end up below rather than to the right of the content

**Comment by ktoso** [comment]
[ ] it's difficult when you go to http://akka.io/blog/ to get comments for the first displayed post. You would expect to be able to click on the title to get into "the article view" to then see the comments, but that is not actually a link.

**Comment by ktoso** [comment]
[ ] don't forget to do the redirect from http://blog.akka.io/ to http://akka.io/blog

**Comment by ktoso** [comment]
-  [ ] make "news" and "articles" on http://akka.io/blog/ actual links such that people can easily filter for those (and find out that they can)

**Comment by patriknw** [comment]
* [ ] it would be nice with a smaller font size for the blog post code snippets, since it's so narrow

**Comment by johanandren** [comment]
@ktoso that'd be the "Alla news" and "All articles" below the list of 5 most recent news or articles?

**Comment by ktoso** [comment]
> @ktoso that'd be the "Alla news" and "All articles" below the list of 5 most recent news or articles?

Hm now I see that; I guess the big "news and articles" really made me want to click that.

**Comment by johanandren** [comment]
I don't mind making those links as well if you think it helps.

**Comment by johanandren** [comment]
I take that back, it's weird that a "Latest Articles" header is a link that goes to "All articles"

**Comment by johanandren** [comment]
- [ ] Code font isn't right

**Comment by johanandren** [comment]
- [] Disqus comments is attached to old urls so doesn't show for moved blog posts

**Comment by 2m** [comment]
Responsiveness is not achieved anymore. Current site:
![current](https://cloud.githubusercontent.com/assets/422086/26440955/44c6237a-4137-11e7-8430-51300dfcd1c5.png)
Mockup of the new theme:
![mockup](https://cloud.githubusercontent.com/assets/422086/26440962/4e209324-4137-11e7-82fd-1219e109daca.png)

**Comment by ktoso** [comment]
- [ ] add explicit indication that there is an rss feed available (small icon somewhere would do)

**Comment by johanandren** [comment]
@2m what browser and screen size? I get it to go in small screen mode in both safari and chrome at < 768px screen width

**Comment by johanandren** [comment]
@ktoso somewhere under `blog/` then I guess? Doesn't feel important enough to go on the landning page and is really a feed for the blog/news.

**Comment by ktoso** [comment]
The icon? Yeah somewhere completely down below :)

**Comment by ktoso** [comment]
Seems we can close this?

**Comment by johanandren** [comment]
Yup.
