### ISSUE TITLE
Community site badges don't work

### ISSUE THREAD

**Issue by ktoso** [akka/akka.github.com#455]
See:

![](https://files.gitter.im/akka/akka/KHJq/image.png)

via gitter:

Mike @Mike62724851_twitter 19:20
There doesn't seem to be any projects indexed under http://akka.io/community/
 

Konrad `ktoso` Malawski @ktoso 19:24
weird, seems scalaindex broke the search syntax we used
could you open a ticket on https://github.com/akka/akka.github.com please?
we’ll take it from there
ping @Mike62724851_twitter , thanks!

**Comment by ktoso** [comment]
Not urgent, but perhaps you'll have an idea how to fix this @2m?

**Comment by ktoso** [comment]
Seems they broke that query somehjow

**Comment by ktoso** [comment]
From duplicate issue on akka/akka by @WadeWaldron 

> On the following page:
> 
> http://akka.io/community/
> 
> There are a series of links to Scaladex. These links are currently returning zero results. This gives the impression that there are no community plugins for Akka.
> 
> This returns no results:
> https://index.scala-lang.org/search?q=keywords:akka-persistence-plugin
> 
> However the following will return results:
> https://index.scala-lang.org/search?q=akka+persistence+plugin
> 
> Seems that the syntax being used for these links is not supported.

The fix should be simple, changing the urls on https://github.com/akka/akka.github.com/blob/master/community/index.html
Could you do that @WadeWaldron?

**Comment by 2m** [comment]
scaladex changed the query from keywords to topics. New links should be:

|Topic|Url|
|-------------|-------------|
|Extensions to Akka|https://index.scala-lang.org/search?topics=akka|
|Extensions to Akka Http|https://index.scala-lang.org/search?topics=akka-http|
|Akka Streams connectors|https://index.scala-lang.org/search?topics=akka-streams|
|Akka Persistence journal and snapshot plugins|https://index.scala-lang.org/search?topics=akka-persistence|

**Comment by WadeWaldron** [comment]
Okay, I have created a PR for this based on the links @2m provided above.

https://github.com/akka/akka.github.com/pull/457
