### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by DiegoReiriz** [akka/akka.github.com#480]
I don't know if this issue should be in this project, but i couldn't find a better place.

There's an error in this [Scala example provided in the documentation](https://doc.akka.io/docs/akka/2.5/stream/stream-quickstart.html#here-is-another-example-that-you-can-edit-and-run-in-the-browser-)

As you can see in the code, all the spaces have been replaced for "+".

I could do the small change to fix it, but i don't know where it should be placed

**Comment by 2m** [comment]
Hi @DiegoReiriz  thanks for reporting the issue. There is a ticket for this issue already which you can find here: https://github.com/akka/akka/issues/24099
