### ISSUE TITLE
Canonical link

### ISSUE THREAD

**Issue by ennru** [akka/akka.github.com#557]
Akka has used `current` for the canonical URL for a while.
I believe it would be better to direct to the major version instead as the page structure may change between major releases.
Google seems to pick majors over the specified URL anyway.

See https://support.google.com/webmasters/answer/139066?hl=en

See https://www.gsqi.com/marketing-blog/google-ignore-rel-canonical-different-content/

**Comment by jrudolph** [comment]
What is the concrete proposal here?

That the canonical links for all pages link to the current major version page? Does that really help when the documentation has different structure? The old versions would then still point to wrong or non-existing pages.

Or is the proposal to have canonical links for each of the major versions and link back from the minor versions to the major ones? That would still introduce multiple versions of the docs to the search engines even if it are only the major ones.

If we want people to always end up at the current version of the docs it would probably be best just to deindex old versions (e.g. by adding the `X-Robots-Tag: noindex` header to all docs pages but the ones we want to show up). The biggest problem is then that old documentation cannot be searched, not even using google (though, that probably neither works currently).

**Comment by ennru** [comment]
This was mostly a proposal to have this discussion.

Within one major the docs tend to keep the same structure is my thinking, so it would be more correct to let all minors within that major point to it.

The "but please use the latest version" will still be there on the site as Javascript, but invisible for search engines.

`noindex` is quite harsh, as you notice.

But let's continue this discussion before we do changes.

**Comment by raboof** [comment]
I think it would be a bad experience to have a google result point to `2.4` only to be greeted with a popup pointing your to `2.5` instead. Also as @jrudolph mentioned there'd be a large chance of duplicate content penalties if we keep both `2.4` and `2.5` indexed separately.

We can fix both by either `noindex`ing all of 2.4, or pointing the canonical links to `current`. When going for `current`, we can catch page structure changes by adding redirects - which I'm sure we will get penalized for, but it might still be better than not having the 2.4 pages indexed at all, plus we want the redirects in place anyway to make the version warning box work.

**Comment by ennru** [comment]
Adding canonical to Akka Persistence Couchbase with https://github.com/akka/akka-persistence-couchbase/pull/203

**Comment by ennru** [comment]
We've come a long way with the rollout of canonical URLs on our pages.
I'll close this overarching issue.
