### ISSUE TITLE
Add canonical links to existing docs

### ISSUE THREAD

**Issue by ennru** [akka/akka.github.com#558]
With enough sed-foo, it might be possible to add canonical links to the existing docs (including scaladocs).
Let's discuss if that's worth the effort.

**Comment by raboof** [comment]
It might be more maintainable to remove any (possibly invalid) canonical links from the HTML pages, and rely on the HTTP headers (already in place for many pages, mentioned e.g. at https://support.google.com/webmasters/answer/139066?hl=en) instead?

Should we be pointing to 'current' or to the latest major version (e.g. 2.5)? I sort of feel like we want to nudge people towards 'current'.

**Comment by ennru** [comment]
For the existing pages, HTTP headers seem easier.
But there is a beauty in standardising on in page links.

The nudging is done by our version warnings. I believe pointing to the major is the right thing to do for redirects.

**Comment by TimMoore** [comment]
For the purposes of Google searches, current does seem right to me. Otherwise, you'd have to rewrite all old docs to point to a new canonical whenever it changes. I don't know if Google would follow chains of canonical references.

**Comment by raboof** [comment]
I think Google indeed punishes/ignores 'chains of references'.

I think @ennru is suggesting to keep the 'canonical' links for all `2.4.x` releases pointing to `2.4`, and not re-pointing them to `2.5`, to somewhat avoid 404's/chains when the page structure changes.

It might be worth taking some 404/chain hit if that allows us to transfer some link value from `2.4` to `current` though...

**Comment by ennru** [comment]
We end up having the same discussions in this and #557. My bad, I guess.

**Comment by ennru** [comment]
I took out my sed sword, wrapped it in bash and added canonicals and descriptions to the existing Akka 2.0, 2.1, 2.2, 2.3 and 2.4 docs. I went with pointing to the corresponding 2.x version for each 2.x.y release, instead of `current` across the board.

**Comment by ennru** [comment]
That made Moz tell me that we have 1.5k fewer pages which lack canonical and description.
