### ISSUE TITLE
Move Akka gRPC to akka.io

### ISSUE THREAD

**Issue by ennru** [akka/akka.github.com#561]

**Comment by ennru** [comment]
Paradox
- [ ] change `project.url`
- [ ] change `canonical.base_url`
- [ ] change Scaladoc URL

akka/akka.github.com
- [ ] change https://github.com/akka/akka.github.com/blob/master/docs/index.html

akka/akka
- [ ] change https://github.com/akka/akka/blob/master/akka-docs/src/main/paradox/cluster-usage.md
- [ ] change https://github.com/akka/akka/blob/master/akka-docs/src/main/paradox/remoting-artery.md
- [ ] change https://github.com/akka/akka/blob/master/akka-docs/src/main/paradox/cluster-dc.md
- [ ] change https://github.com/akka/akka/blob/master/akka-docs/src/main/paradox/cluster-client.md
- [ ] change https://github.com/akka/akka/blob/master/akka-docs/src/main/paradox/remoting.md
- [ ] change https://github.com/akka/akka/blob/master/akka-docs/src/main/paradox/common/other-modules.md

**Comment by ennru** [comment]
I've now deployed 0.5.0, 0.6.0, and 0.6.1 docs on akka.io
https://doc.akka.io/docs/akka-grpc/current/

**Comment by ennru** [comment]
To automate the documentation and API deployment we'd need to 
- [ ] use sbt-site to run Paradox and unidoc to one artefact/directory
- [ ] Add rsync support
- [ ] set up Travis secrets for rsync

**Comment by raboof** [comment]
I'm not sure we need `sbt-site`, it might be simple enough to have the rsync task depend on both paradox and unidoc? Do we have positive experiences with it in other projects?

**Comment by ennru** [comment]
Let's discuss `sbt-site` use. It helps us in Alpakka. Another good feature is that the links from Paradox to the API actually work locally when using `previewSite`.

**Comment by raboof** [comment]
Sounds good to me!

**Comment by ennru** [comment]
Done.
