### ISSUE TITLE
Fix Javadoc for Akka snapshots

### ISSUE THREAD

**Issue by ennru** [akka/akka.github.com#563]
docs/other-releases.md points to https://doc.akka.io/japi/akka/snapshot/

**Comment by johanandren** [comment]
I think we should rather remove the link than start publishing api-docs for snapshots

**Comment by ennru** [comment]
Ah, I thought they used to be there and it is just temporarily broken.

**Comment by ennru** [comment]
But now the snapshot Javadoc is there.
Closing.
