### ISSUE TITLE
Make sure top landing pages exist on akka.io

### ISSUE THREAD

**Issue by ennru** [akka/akka.github.com#565]
One of those is https://akka.io/downloads/ which doesn't exist.

**Comment by TimMoore** [comment]
It could redirect to https://akka.io/try-akka/

**Comment by TimMoore** [comment]
(It did exist in a previous version of the site: http://web.archive.org/web/20170118121928/http://akka.io/downloads/)

**Comment by johanandren** [comment]
It was essentially replaced with the docs page, because it had links to the docs (and then the super-zip that we don't do anymore). Not sure if try-akka is a better redirect, perhaps it is.

**Comment by TimMoore** [comment]
I don't have a strong opinion about where it goes, but the information we got is that redirect anywhere is better than 404 for search ranking purposes (unless it creates a chain of redirects, which is also penalized). It could even redirect to the home page.

**Comment by ennru** [comment]
Note that the link without the `docs` subdomain is still broken 
https://akka.io/downloads/

**Comment by raboof** [comment]
> the link without the docs subdomain is still broken https://akka.io/downloads/

Indeed - https://akka.io/downloads works but https://akka.io/downloads/ doesn't - which surprises me because it works fine when I try it locally with `bundle exec jekyll serve --baseurl '' --future`.

Locally, when I fix it for https://akka.io/downloads/ it breaks for https://akka.io/downloads. I'll hold off making further changes until I get access to Moz.

> And https://doc.akka.io/downloads/ is possibly something we want to hide?

I don't think there's anything sensitive there, but it does look pretty outdated.

**Comment by ennru** [comment]
> > And [doc.akka.io/downloads](https://doc.akka.io/downloads/) is possibly something we want to hide?
> 
> I don't think there's anything sensitive there, but it does look pretty outdated.

It could make people believe it is still relevant. Redirecting to `try-akka` makes more sense, I guess.

**Comment by ennru** [comment]
https://github.com/akka/akka.github.com/pull/653

**Comment by ennru** [comment]
Now that #653 is merged the redirect from `downloads/` which already was in `try-akka/index.html` started working!?
