### ISSUE TITLE
Redirects from Techhub for older Alpakka versions

### ISSUE THREAD

**Issue by ennru** [akka/akka.github.com#567]
The Internet still points to very old versions of the Alpakka docs. Techhub should redirect to current on akka.io.

**Comment by 2m** [comment]
Configured gustav to redirect everything from `0.1` to `0.16` to `current`:

```
RedirectMatch 301 ^/(docs|api)/alpakka/0.(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16)(/?|/.*)$ https://doc.akka.io/$1/alpakka/current$3
```
