### ISSUE TITLE
Redirects for "akka-stream-and-http-experimental"

### ISSUE THREAD

**Issue by ennru** [akka/akka.github.com#578]
Examples that 404 right now:

https://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala.html
https://doc.akka.io/docs/akka-stream-and-http-experimental/1.0/scala/stream-integrations.html

https://doc.akka.io/docs/akka-stream-and-http-experimental/2.0.2/java/migration-guide-1.0-2.x-java.html

https://doc.akka.io/docs/akka-stream-and-http-experimental/2.0.3/scala.html

https://doc.akka.io/api/akka-stream-and-http-experimental/0.7/#akka.stream.scaladsl2.package

These links stem from old blog posts.

Where should we send the curious search engine instead?

**Comment by raboof** [comment]
I already added redirects for links that can be recognized as Akka HTTP or Akka Streams.

For leftovers like these, it might be best to let them remain 404's and peter out (fixing old blog posts if they're our own)?

**Comment by ennru** [comment]
Ok, these seem to come from our blog posts. 
Let's rewrite them there.

**Comment by ennru** [comment]
The links in the blog posts are updated.
