### ISSUE TITLE
Create/generate select version pages

### ISSUE THREAD

**Issue by ennru** [akka/akka.github.com#585]
### Short description

Generate something nicer for version selection in
- [ ] https://doc.akka.io/docs/akka/
- [ ] https://doc.akka.io/docs/akka-http/
- [ ] https://doc.akka.io/docs/alpakka/
...

**Comment by johanandren** [comment]
Could perhaps be good with a lower limit and not list old enough stuff for the search indexers to pick up at all?

**Comment by ennru** [comment]
We made those pages redirect to `current` instead.
