### ISSUE TITLE
warnOldDocs.js must be aware of akka-http move

### ISSUE THREAD

**Issue by ktoso** [akka/akka.github.com#597]
As reported by Devon Stewart @blast-hardcheese http://doc.akka.io/docs/akka/2.4.9/scala/http/routing-dsl/routes.html

**Comment by patriknw** [comment]
@raboof  not sure if this is still relevant, otherwise please close

**Comment by johanandren** [comment]
I think the issue is that the old Akka HTTP docs were a part of the Akka Docs, so you get a redirect warning saying that you should look at latest Akka rather than latest Akka HTTP.

**Comment by blast-hardcheese** [comment]
It used to be extremely difficult to Google the akka-http docs. It's still difficult to get to the scaladocs from any given akka-http docs page, fwiw. Largely ungooglable when you search for `"Directives.scala"`, for instance.

**Comment by raboof** [comment]
> It's still difficult to get to the scaladocs from any given akka-http docs page, fwiw. Largely ungooglable when you search for "Directives.scala", for instance.

Agreed! To improve on this, we've made it much easier to link from the docs markdown to the javadoc/scaladoc with the `@apidoc` paradox directive, and we've been working on SEO for all akka.io pages (fixing 404's, canonicals, duplicate content, etc). Still, much more work to do. One thing on my 'dream list' would be to add links from code snippets to the API docs (either via scalafiddle or 'directly'). Any other recommendations? Anything you could contribute?

**Comment by raboof** [comment]
I don't think it's worth it to fix `warnOldDocs.js` to understand to redirect to akka-http for http pages, and instead we should focus on adding the right `canonical` links so google points to the 'current' versions of the docs.

**Comment by raboof** [comment]
Feel free to open new issues with idea for improvement in this area, though!

**Comment by blast-hardcheese** [comment]
@raboof Definitely understandable, and I was surprised to see the activity on such an old issue 😄

A simple direct link from the index of the documentation to the root of the scaladoc for the same version would go _very_ far for me. I get a lot more out of the type signatures than reading prose, as I've been working with akka-http for a number of years.

Additionally, a landing page for all the different versions of published scaladoc would be excellent.

As an exercise, attempt to get to the related scaladoc from https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/index.html .
I got:

1. Click `Akka HTTP` in the nav bar
1. scroll down to `10. Reference`
1. click `API Documentation`
1. click `Scaladoc`
1. type `Directives`
1. scroll through to find the related object or trait in the search results

There's not always an obvious API to link to directly from documentation pages. If mdoc supports deep analysis on object/method metadata, embedding links directly into the code snippet would be wild.

**Comment by raboof** [comment]
> A simple direct link from the index of the documentation to the root of the scaladoc for the same version would go very far for me

Yeah - I wonder if we should just put (perhaps a little less high version of) the banner on top of https://discuss.akka.io on top of all our reference and API documentation pages as well

**Comment by blast-hardcheese** [comment]
It's funny, I never would have imagined those different sections are actually menus. There's no way to use them on mobile, it just looks like a fancy graphic

**Comment by blast-hardcheese** [comment]
That being said, yes, that would be excellent!
