### ISSUE TITLE
SEO: 404 error for Akka Persistence Couchbase API documentation

### ISSUE THREAD

**Issue by TimMoore** [akka/akka.github.com#622]
We got a Google Search Console alert for this URL:

https://doc.akka.io/api/akka-persistence-couchbase/current

It returns 404, but appears in https://doc.akka.io/sitemap.xml

**Comment by ennru** [comment]
There is something missing in the deployment, the API docs aren't there. I'll have a look.

**Comment by ennru** [comment]
@johanandren voted for not deploying API docs for it as users normally don't program against those APIs. I'll remove it from the site map and redirect the existing 1.0-RC2 deployment somewhere.

**Comment by ennru** [comment]
I removed it from the sitemap and `api/akka-persistence-couchbase` now redirects to the docs instead.
