### ISSUE TITLE
Infinite redirect loop

### ISSUE THREAD

**Issue by TimMoore** [akka/akka.github.com#624]
Google reported a redirect error on https://doc.akka.io/docs/akka/snapshot/guide/introduction.html

It looks like there's an infinite recursion in a URL rewrite rule. When I load it in Chrome it fails with ERR_TOO_MANY_REDIRECTS on
http://doc.akka.io/docs/akka/snapshot/typed/typed/typed/typed/typed/typed/typed/typed/typed/typed/guide/introduction.html

**Comment by TimMoore** [comment]
Similarly on https://doc.akka.io/docs/akka/snapshot/guide/tutorial_1.html and likely others.

**Comment by raboof** [comment]
manually fixed on the docs server, but will get overwritten again when the nightly runs before https://github.com/akka/akka/pull/27341 is merged. Unfortunately to test you'll have to clear your browser cache (or use another browser, perhaps an incognito tab)

**Comment by TimMoore** [comment]
It did work a few minutes ago, but looks like it has been overwritten already.
