### ISSUE TITLE
Roll-out of Lightbend banner on doc.akka.io

### ISSUE THREAD

**Issue by ennru** [akka/akka.github.com#629]
Update the akka-paradox theme and redeploy current docs for

- [x] akka/akka
- [x] akka/akka-http 
- [x] akka/alpakka-kafka
- [x] akka/alpakka
- [x] akka/alpakka-samples
- [x] akka/akka-management
- [x] akka/akka-grpc 
- [x] akka/akka-persistence-cassandra
- [x] akka/akka-persistence-couchbase
- [x] lightbend/akka-enhancements

**Comment by raboof** [comment]
new theme with the banner is in akka-paradox version 0.21

**Comment by ennru** [comment]
Make that version 0.22 to get hopefully avoid caching issues a bit more.

**Comment by theotown** [comment]
Eagerly watching this list grow! Great work, Enno and team :-)

**Comment by ennru** [comment]
I'll stop here as we discovered https://github.com/akka/akka-paradox/issues/70

**Comment by ennru** [comment]
Ok, updated the ones I did yesterday to 0.23 now.

**Comment by theotown** [comment]
Hey Enno, thanks for everything thus far. Can I ask for an update on the addition of the banner to the remaining categories? How can I help?

**Comment by ennru** [comment]
All current Akka sites are updated now.

**Comment by theotown** [comment]
AMAZING work Enno. Thank you for taking this on so seriously!!

**Comment by patriknw** [comment]
Thanks for all this work @ennru
