### ISSUE TITLE
Search box z-index stacking issue

### ISSUE THREAD

**Issue by TimMoore** [akka/akka.github.com#632]
Recently, the search results box on doc.akka.io pops up behind some of the page content:

<img width="695" alt="Screen Shot 2019-08-21 at 10 19 25 am" src="https://user-images.githubusercontent.com/44385/63738630-7b0de280-c8c9-11e9-8de0-3e5bd0f47bdc.png">

I haven't looked exhaustively, but I see this in the Akka 2.5.25 docs and Akka HTTP current docs but _not_ in Akka HTTP 10.0.15 docs.

**Comment by johanandren** [comment]
Can repeat in Firefox and Chrome, Safari looks fine but has stopped scrolling the content independently of the navigation bar.

**Comment by ennru** [comment]
@rasummer Would you have the time to look into this?
