### ISSUE TITLE
deploy akka.io to gustav

### ISSUE THREAD

**Issue by raboof** [akka/akka.github.com#682]
It is a bit weird that we publish our docs from gustav under 'doc.akka.io', but our main site from github pages under 'akka.io'.

It would be nice to harmonize this. Since hosting the docs via github pages doesn't seem feasible (it's a lot of files because we keep around docs for old versions), let's try publishing the akka.io docs to gustav instead.

**Comment by raboof** [comment]
#683 for publishing from travis to gustav for each merge to master.

I have also made the necessary configurations on gustav, so after that's ready to be merged I think we can change over the domain name. Testing appreciated :) (e.g. `curl --insecure --header "Host: akka.io" http://gustav.akka.io`)

(This does not yet merge akka.io and doc.akka.io, that's for another issue ;) )

**Comment by ennru** [comment]
#615 might be the reason why I immediately liked this idea...

**Comment by ennru** [comment]
Just came to think about https://akka.io/alpakka-samples which is published to Github pages as well.

**Comment by ennru** [comment]
Fixed with https://github.com/akka/akka.github.com/pull/683, https://github.com/akka/alpakka-samples/pull/55, https://github.com/akka/alpakka-samples/pull/56, and https://github.com/akka/alpakka-samples/pull/57
